-- Clear existing data
DELETE FROM rule_conditions;
DELETE FROM rules;
DELETE FROM questions;

-- Questions
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('米国拠点の業務に深く関連する2年以上の業務経験があります', '米国拠点の業務に深く関連する2年以上の業務経験があります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('理系の大学院卒で、米国拠点の技術系の業務に深く関連する3年以上の業務経験があります', '理系の大学院卒で、米国拠点の技術系の業務に深く関連する3年以上の業務経験があります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('Blanket Lビザのマネージャーまたはスタッフの条件を満たします', 'Blanket Lビザのマネージャーまたはスタッフの条件を満たします', 'L', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('研修にOJTが含まれます', '研修にOJTが含まれます', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('Bビザの申請条件を満たす（ESTAの認証は通らない）', 'Bビザの申請条件を満たす（ESTAの認証は通らない）', 'B', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('会社がEビザの投資の条件を満たします', '会社がEビザの投資の条件を満たします', 'E', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('アメリカの会社に販売した装置や設備のための作業をします', 'アメリカの会社に販売した装置や設備のための作業をします', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('申請者に研修に必要な英語力はあります', '申請者に研修に必要な英語力はあります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('研修内容は商用の範囲です', '研修内容は商用の範囲です', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('研修期間は６か月以内です', '研修期間は６か月以内です', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('EビザTDY(short-term needs)の条件を満たします', 'EビザTDY(short-term needs)の条件を満たします', 'E', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('理系の学部卒で、米国拠点の技術系の業務に深く関連する4年以上の業務経験があります', '理系の学部卒で、米国拠点の技術系の業務に深く関連する4年以上の業務経験があります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('マネジメントが求められるプロジェクトマネージャーなどの2年以上の経験があります', 'マネジメントが求められるプロジェクトマネージャーなどの2年以上の経験があります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('アメリカでの業務はspecialized knowledgeを必要とします', 'アメリカでの業務はspecialized knowledgeを必要とします', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('貿易による利益が会社の経費の80％以上をカバーしています', '貿易による利益が会社の経費の80％以上をカバーしています', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('申請者がLビザ（Individual）の条件を満たします', '申請者がLビザ（Individual）の条件を満たします', 'L', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('アメリカ以外からアメリカへのグループ内での異動です', 'アメリカ以外からアメリカへのグループ内での異動です', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('装置や設備の販売を示す契約書や発注書があります', '装置や設備の販売を示す契約書や発注書があります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('申請者と会社の国籍が同じです', '申請者と会社の国籍が同じです', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('Lビザ 質問6', 'Lビザ 質問6', 'L', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('申請者がBlanket Lビザの条件を満たします', '申請者がBlanket Lビザの条件を満たします', 'L', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('申請者がEビザのスタッフの条件を満たします', '申請者がEビザのスタッフの条件を満たします', 'E', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('2年以上のマネージャー経験があります', '2年以上のマネージャー経験があります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('経営企画のマネージャーなど、米国拠点の経営に関わるポジションに就きます', '経営企画のマネージャーなど、米国拠点の経営に関わるポジションに就きます', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('2年以内の期間で、目的を限定した派遣理由を説明できます', '2年以内の期間で、目的を限定した派遣理由を説明できます', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('アメリカでの活動は商用の範囲です', 'アメリカでの活動は商用の範囲です', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('マネジメント経験が2年以上あります', 'マネジメント経験が2年以上あります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('まだ十分な売り上げがなく、これまでに人件費などのランニングコストを含め、30万ドル以上支出しています', 'まだ十分な売り上げがなく、これまでに人件費などのランニングコストを含め、30万ドル以上支出しています', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('大卒以上で、専攻内容と業務内容が異なりますが、実務経験が3年以上あります', '大卒以上で、専攻内容と業務内容が異なりますが、実務経験が3年以上あります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('評価・雇用に責任を持つ複数のフルタイムのスタッフを部下に持つマネージャー以上のポジションに就きます', '評価・雇用に責任を持つ複数のフルタイムのスタッフを部下に持つマネージャー以上のポジションに就きます', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('大卒以上で、専攻内容と業務内容が一致しています', '大卒以上で、専攻内容と業務内容が一致しています', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('30万ドル以上で企業を買収した会社か、買収された会社です', '30万ドル以上で企業を買収した会社か、買収された会社です', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('アメリカにある子会社が1,000人以上ローカル採用をしています', 'アメリカにある子会社が1,000人以上ローカル採用をしています', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('Blanket Lビザスタッフの条件を満たします', 'Blanket Lビザスタッフの条件を満たします', 'L', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('Bビザの申請条件を満たす（ESTAの認証は通る）', 'Bビザの申請条件を満たす（ESTAの認証は通る）', 'B', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('米国拠点の業務に深く関連する5年以上の業務経験があります', '米国拠点の業務に深く関連する5年以上の業務経験があります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('1回の滞在期間は6か月を越えません', '1回の滞在期間は6か月を越えません', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('アメリカでの業務はマネージャーとみなされます', 'アメリカでの業務はマネージャーとみなされます', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('会社の行う貿易の50％が日米間です', '会社の行う貿易の50％が日米間です', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('申請者がEビザのマネージャー以上の条件を満たします', '申請者がEビザのマネージャー以上の条件を満たします', 'E', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('CEOなどのオフィサーのポジションに就きます', 'CEOなどのオフィサーのポジションに就きます', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('アメリカでは大卒、フルタイムの部下が2名以上います', 'アメリカでは大卒、フルタイムの部下が2名以上います', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('会社設立のために、30万ドル以上支出しました（不動産を除く）', '会社設立のために、30万ドル以上支出しました（不動産を除く）', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('直近3年のうち1年以上、アメリカ以外のグループ会社に所属していました', '直近3年のうち1年以上、アメリカ以外のグループ会社に所属していました', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('会社がBlanket Lビザの条件を満たします', '会社がBlanket Lビザの条件を満たします', 'L', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('1回の滞在期間は90日を越えます', '1回の滞在期間は90日を越えます', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('H-1Bビザが必要な専門性の高い作業をします', 'H-1Bビザが必要な専門性の高い作業をします', 'B', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('米国拠点のポジションの業務に深く関連する業務の経験が2年以上あります', '米国拠点のポジションの業務に深く関連する業務の経験が2年以上あります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('減価償却前の設備や建物が30万ドル以上財務諸表の資産に計上されています', '減価償却前の設備や建物が30万ドル以上財務諸表の資産に計上されています', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('マネージャーとしての経験があります', 'マネージャーとしての経験があります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('specialized knowledgeがあります', 'specialized knowledgeがあります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('申請者がEビザの条件を満たします', '申請者がEビザの条件を満たします', 'E', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('会社の行う貿易は継続的です', '会社の行う貿易は継続的です', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('研修期間は18か月以内です', '研修期間は18か月以内です', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('大卒以上ではありませんが、実務経験が(高卒は12年以上、高専卒は3年以上）あります', '大卒以上ではありませんが、実務経験が(高卒は12年以上、高専卒は3年以上）あります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('アメリカにある子会社の売り上げの合計が25百万ドル以上です', 'アメリカにある子会社の売り上げの合計が25百万ドル以上です', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('マネージャー以上のポジションの業務を遂行する十分な能力があります', 'マネージャー以上のポジションの業務を遂行する十分な能力があります', NULL, 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('会社がEビザの条件を満たします', '会社がEビザの条件を満たします', 'E', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('1年間に10人以上Lビザのペティション申請をしています', '1年間に10人以上Lビザのペティション申請をしています', 'L', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('米国拠点でEビザでマネージャー以上として認められるポジションに就きます', '米国拠点でEビザでマネージャー以上として認められるポジションに就きます', 'E', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('会社がEビザの貿易の条件を満たします', '会社がEビザの貿易の条件を満たします', 'E', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('Lビザ（Individual）のマネージャーまたはスタッフの条件を満たします', 'Lビザ（Individual）のマネージャーまたはスタッフの条件を満たします', 'L', 0);
INSERT INTO questions (fact_name, question_text, visa_type, priority) VALUES ('Blanket Lビザのマネージャーの条件を満たします', 'Blanket Lビザのマネージャーの条件を満たします', 'L', 0);

-- Rules
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_1', 'E', 'Eビザでの申請ができます', TRUE, 'AND', 100);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_2', 'E', '会社がEビザの条件を満たします', TRUE, 'OR', 90);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_3', 'E', '会社がEビザの投資の条件を満たします', TRUE, 'OR', 80);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_4', 'E', '会社がEビザの貿易の条件を満たします', TRUE, 'AND', 80);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_5', 'E', '申請者がEビザの条件を満たします', TRUE, 'OR', 70);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_6', 'E', '申請者がEビザのマネージャー以上の条件を満たします', TRUE, 'AND', 60);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_7', 'E', '米国拠点でEビザでマネージャー以上として認められるポジションに就きます', TRUE, 'OR', 50);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_8', NULL, 'マネージャー以上のポジションの業務を遂行する十分な能力があります', TRUE, 'AND', 50);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_9', NULL, 'マネジメント経験が2年以上あります', TRUE, 'OR', 40);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_10', 'E', '申請者がEビザのスタッフの条件を満たします', TRUE, 'OR', 60);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_11', 'E', 'EビザTDY(short-term needs)の条件を満たします', TRUE, 'AND', 60);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_12', 'L', 'Blanket Lビザでの申請ができます', TRUE, 'AND', 100);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_13', 'L', '会社がBlanket Lビザの条件を満たします', TRUE, 'OR', 80);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_14', 'L', '申請者がBlanket Lビザの条件を満たします', TRUE, 'AND', 70);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_15', 'L', 'Blanket Lビザのマネージャーまたはスタッフの条件を満たします', TRUE, 'OR', 60);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_16', 'L', 'Blanket Lビザのマネージャーの条件を満たします', TRUE, 'AND', 50);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_17', 'L', 'Blanket Lビザスタッフの条件を満たします', TRUE, 'AND', 50);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_18', 'L', 'Lビザ（Individual）での申請ができます', TRUE, 'AND', 100);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_19', 'L', '申請者がLビザ（Individual）の条件を満たします', TRUE, 'AND', 70);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_20', 'L', 'Lビザ（Individual）のマネージャーの条件を満たします', TRUE, 'AND', 50);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_21', 'L', 'Lビザ（Individual）のスタッフの条件を満たします', TRUE, 'AND', 50);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_22', 'H-1B', 'H-1Bビザでの申請ができます', TRUE, 'OR', 100);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_23', 'B', 'Bビザの申請ができます', TRUE, 'OR', 101);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_24', 'B', 'Bビザの申請条件を満たす（ESTAの認証は通る）', TRUE, 'AND', 80);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_25', 'B', 'Bビザの申請条件を満たす（ESTAの認証は通らない）', TRUE, 'AND', 80);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_26', 'B', '契約書に基づくBビザの申請ができます', TRUE, 'AND', 100);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_27', 'H-1B', 'B-1 in lieu of H-1Bビザの申請ができます', TRUE, 'AND', 100);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_28', 'J-1', 'J-1ビザの申請ができます', TRUE, 'AND', 100);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_29', 'B', 'Bビザの申請ができます', TRUE, 'AND', 100);
INSERT INTO rules (rule_id, visa_type, conclusion, conclusion_value, operator, priority) VALUES ('rule_30', 'B', 'B-1 in lieu of H3ビザの申請ができます', TRUE, 'AND', 100);

-- Rule Conditions
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '申請者と会社の国籍が同じです', TRUE FROM rules WHERE rule_id = 'rule_1';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '会社がEビザの条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_1';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '申請者がEビザの条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_1';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '会社がEビザの投資の条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_2';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '会社がEビザの貿易の条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_2';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '減価償却前の設備や建物が30万ドル以上財務諸表の資産に計上されています', TRUE FROM rules WHERE rule_id = 'rule_3';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '30万ドル以上で企業を買収した会社か、買収された会社です', TRUE FROM rules WHERE rule_id = 'rule_3';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'まだ十分な売り上げがなく、これまでに人件費などのランニングコストを含め、30万ドル以上支出しています', TRUE FROM rules WHERE rule_id = 'rule_3';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '会社設立のために、30万ドル以上支出しました（不動産を除く）', TRUE FROM rules WHERE rule_id = 'rule_3';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '会社の行う貿易の50％が日米間です', TRUE FROM rules WHERE rule_id = 'rule_4';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '会社の行う貿易は継続的です', TRUE FROM rules WHERE rule_id = 'rule_4';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '貿易による利益が会社の経費の80％以上をカバーしています', TRUE FROM rules WHERE rule_id = 'rule_4';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '申請者がEビザのマネージャー以上の条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_5';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '申請者がEビザのスタッフの条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_5';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'EビザTDY(short-term needs)の条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_5';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '米国拠点でEビザでマネージャー以上として認められるポジションに就きます', TRUE FROM rules WHERE rule_id = 'rule_6';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'マネージャー以上のポジションの業務を遂行する十分な能力があります', TRUE FROM rules WHERE rule_id = 'rule_6';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'CEOなどのオフィサーのポジションに就きます', TRUE FROM rules WHERE rule_id = 'rule_7';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '経営企画のマネージャーなど、米国拠点の経営に関わるポジションに就きます', TRUE FROM rules WHERE rule_id = 'rule_7';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '評価・雇用に責任を持つ複数のフルタイムのスタッフを部下に持つマネージャー以上のポジションに就きます', TRUE FROM rules WHERE rule_id = 'rule_7';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '米国拠点のポジションの業務に深く関連する業務の経験が2年以上あります', TRUE FROM rules WHERE rule_id = 'rule_8';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'マネジメント経験が2年以上あります', TRUE FROM rules WHERE rule_id = 'rule_8';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '2年以上のマネージャー経験があります', TRUE FROM rules WHERE rule_id = 'rule_9';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'マネジメントが求められるプロジェクトマネージャーなどの2年以上の経験があります', TRUE FROM rules WHERE rule_id = 'rule_9';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '理系の大学院卒で、米国拠点の技術系の業務に深く関連する3年以上の業務経験があります', TRUE FROM rules WHERE rule_id = 'rule_10';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '理系の学部卒で、米国拠点の技術系の業務に深く関連する4年以上の業務経験があります', TRUE FROM rules WHERE rule_id = 'rule_10';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '米国拠点の業務に深く関連する5年以上の業務経験があります', TRUE FROM rules WHERE rule_id = 'rule_10';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '2年以内の期間で、目的を限定した派遣理由を説明できます', TRUE FROM rules WHERE rule_id = 'rule_11';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '米国拠点の業務に深く関連する2年以上の業務経験があります', TRUE FROM rules WHERE rule_id = 'rule_11';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'アメリカ以外からアメリカへのグループ内での異動です', TRUE FROM rules WHERE rule_id = 'rule_12';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '会社がBlanket Lビザの条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_12';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '申請者がBlanket Lビザの条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_12';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'アメリカにある子会社の売り上げの合計が25百万ドル以上です', TRUE FROM rules WHERE rule_id = 'rule_13';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'アメリカにある子会社が1,000人以上ローカル採用をしています', TRUE FROM rules WHERE rule_id = 'rule_13';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '1年間に10人以上Lビザのペティション申請をしています', TRUE FROM rules WHERE rule_id = 'rule_13';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '直近3年のうち1年以上、アメリカ以外のグループ会社に所属していました', TRUE FROM rules WHERE rule_id = 'rule_14';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'Blanket Lビザのマネージャーまたはスタッフの条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_14';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'Blanket Lビザのマネージャーの条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_15';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'Blanket Lビザスタッフの条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_15';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'マネージャーとしての経験があります', TRUE FROM rules WHERE rule_id = 'rule_16';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'アメリカでの業務はマネージャーとみなされます', TRUE FROM rules WHERE rule_id = 'rule_16';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'specialized knowledgeがあります', TRUE FROM rules WHERE rule_id = 'rule_17';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'アメリカでの業務はspecialized knowledgeを必要とします', TRUE FROM rules WHERE rule_id = 'rule_17';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'アメリカ以外からアメリカへのグループ内での異動です', TRUE FROM rules WHERE rule_id = 'rule_18';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '申請者がLビザ（Individual）の条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_18';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '直近3年のうち1年以上、アメリカ以外のグループ会社に所属していました', TRUE FROM rules WHERE rule_id = 'rule_19';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'Lビザ（Individual）のマネージャーまたはスタッフの条件を満たします', TRUE FROM rules WHERE rule_id = 'rule_19';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'Lビザ 質問6', TRUE FROM rules WHERE rule_id = 'rule_19';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'マネージャーとしての経験があります', TRUE FROM rules WHERE rule_id = 'rule_20';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'アメリカでの業務はマネージャーとみなされます', TRUE FROM rules WHERE rule_id = 'rule_20';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'アメリカでは大卒、フルタイムの部下が2名以上います', TRUE FROM rules WHERE rule_id = 'rule_20';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'specialized knowledgeがあります', TRUE FROM rules WHERE rule_id = 'rule_21';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'アメリカでの業務はspecialized knowledgeを必要とします', TRUE FROM rules WHERE rule_id = 'rule_21';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '大卒以上で、専攻内容と業務内容が一致しています', TRUE FROM rules WHERE rule_id = 'rule_22';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '大卒以上で、専攻内容と業務内容が異なりますが、実務経験が3年以上あります', TRUE FROM rules WHERE rule_id = 'rule_22';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '大卒以上ではありませんが、実務経験が(高卒は12年以上、高専卒は3年以上）あります', TRUE FROM rules WHERE rule_id = 'rule_22';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'Bビザの申請条件を満たす（ESTAの認証は通る）', TRUE FROM rules WHERE rule_id = 'rule_23';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'Bビザの申請条件を満たす（ESTAの認証は通らない）', TRUE FROM rules WHERE rule_id = 'rule_23';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'アメリカでの活動は商用の範囲です', TRUE FROM rules WHERE rule_id = 'rule_24';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '1回の滞在期間は90日を越えます', TRUE FROM rules WHERE rule_id = 'rule_24';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '1回の滞在期間は6か月を越えません', TRUE FROM rules WHERE rule_id = 'rule_24';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'アメリカでの活動は商用の範囲です', TRUE FROM rules WHERE rule_id = 'rule_25';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '1回の滞在期間は6か月を越えません', TRUE FROM rules WHERE rule_id = 'rule_25';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'アメリカの会社に販売した装置や設備のための作業をします', TRUE FROM rules WHERE rule_id = 'rule_26';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '装置や設備の販売を示す契約書や発注書があります', TRUE FROM rules WHERE rule_id = 'rule_26';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '1回の滞在期間は6か月を越えません', TRUE FROM rules WHERE rule_id = 'rule_26';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, 'H-1Bビザが必要な専門性の高い作業をします', TRUE FROM rules WHERE rule_id = 'rule_27';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '1回の滞在期間は6か月を越えません', TRUE FROM rules WHERE rule_id = 'rule_27';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '研修にOJTが含まれます', TRUE FROM rules WHERE rule_id = 'rule_28';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '研修期間は18か月以内です', TRUE FROM rules WHERE rule_id = 'rule_28';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '申請者に研修に必要な英語力はあります', TRUE FROM rules WHERE rule_id = 'rule_28';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '研修内容は商用の範囲です', TRUE FROM rules WHERE rule_id = 'rule_29';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '研修期間は６か月以内です', TRUE FROM rules WHERE rule_id = 'rule_29';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '研修内容は商用の範囲です', TRUE FROM rules WHERE rule_id = 'rule_30';
INSERT INTO rule_conditions (rule_id, fact_name, expected_value) SELECT id, '研修期間は６か月以内です', TRUE FROM rules WHERE rule_id = 'rule_30';
